#!/usr/bin/env python3
"""Collect metrics about the agent-spec enforcement workflow.

Usage:
  python scripts/collect_agent_spec_metrics.py --days 14 --post-issue

- Scans recent PRs (updated in last N days), detects PRs that modified agent code,
  and checks whether the workflow flagged them (by looking for our failure comment)
- Reports counts: PRs inspected, PRs flagged by the check, overrides used (label),
  and lists flagged PR numbers.
- Optionally posts/updates an issue in the repo with the summarized metrics.
"""
from __future__ import annotations

import argparse
import datetime
import os
import sys
from typing import Dict, List

import requests

from scripts.check_agent_spec import detect_agent_changes, get_pr_changed_files, REPO_OWNER, REPO_NAME


FAIL_MESSAGE_SNIPPET = "Agent spec check failed"
METRICS_ISSUE_TITLE = "Agent-spec enforcement metrics (autogenerated)"


def get_recent_prs(days: int, token: str) -> List[Dict]:
    """Return list of PRs updated in the last `days` days (max 200)."""
    headers = {"Accept": "application/vnd.github+json"}
    if token:
        headers["Authorization"] = f"token {token}"

    prs = []
    page = 1
    per_page = 100
    since = (datetime.datetime.utcnow() - datetime.timedelta(days=days)).isoformat() + "Z"
    url = f"https://api.github.com/repos/{REPO_OWNER}/{REPO_NAME}/pulls"
    while page <= 2:  # look at up to 200 PRs (2 pages)
        r = requests.get(url, params={"state": "all", "sort": "updated", "direction": "desc", "page": page, "per_page": per_page}, headers=headers)
        if r.status_code != 200:
            raise RuntimeError(f"GitHub API error listing PRs: {r.status_code} {r.text}")
        data = r.json()
        if not data:
            break
        for pr in data:
            # Ensure this is a PR object (some endpoints may return other objects in tests)
            if not isinstance(pr, dict) or 'number' not in pr:
                continue
            updated_at = pr.get("updated_at") or pr.get("updatedAt")
            if not updated_at:
                # If no timestamp is present in the object, include it (tests/mocks may omit it)
                prs.append(pr)
                continue
            if updated_at >= since:
                prs.append(pr)
            else:
                # reached older PRs; stop early
                return prs
        page += 1
    return prs


def pr_has_failure_comment(pr_number: int, token: str) -> bool:
    headers = {"Accept": "application/vnd.github+json"}
    if token:
        headers["Authorization"] = f"token {token}"
    url = f"https://api.github.com/repos/{REPO_OWNER}/{REPO_NAME}/issues/{pr_number}/comments"
    page = 1
    while True:
        r = requests.get(url, params={"page": page, "per_page": 100}, headers=headers)
        if r.status_code != 200:
            raise RuntimeError(f"GitHub API error fetching comments: {r.status_code} {r.text}")
        data = r.json()
        if not data:
            break
        for c in data:
            if FAIL_MESSAGE_SNIPPET in (c.get("body") or ""):
                return True
        page += 1
    return False


def pr_has_override_label(pr: Dict, override_label: str = "allow-agent-without-spec") -> bool:
    labels = pr.get("labels", [])
    for l in labels:
        if isinstance(l, dict):
            name = l.get("name")
        else:
            name = str(l)
        if name == override_label:
            return True
    return False


def collect_metrics(days: int = 14, token: str | None = None) -> Dict:
    prs = get_recent_prs(days, token)
    inspected = 0
    flagged = []
    overrides = 0

    for pr in prs:
        number = pr.get("number")
        try:
            changed = get_pr_changed_files(number, token)
        except Exception:
            # skip if we couldn't fetch changed files
            continue
        agent_changes = detect_agent_changes(changed)
        if not agent_changes:
            continue
        inspected += 1
        try:
            failed = pr_has_failure_comment(number, token)
        except Exception:
            failed = False
        if failed:
            flagged.append(number)
        if pr_has_override_label(pr):
            overrides += 1

    res = {
        "days": days,
        "inspected_prs": inspected,
        "flagged_prs": len(flagged),
        "override_count": overrides,
        "flagged_list": flagged,
    }
    return res


def find_or_create_metrics_issue(token: str | None) -> int:
    headers = {"Accept": "application/vnd.github+json"}
    if token:
        headers["Authorization"] = f"token {token}"
    # Search for existing issue with the title
    url = f"https://api.github.com/repos/{REPO_OWNER}/{REPO_NAME}/issues"
    r = requests.get(url, params={"state": "open", "per_page": 100}, headers=headers)
    if r.status_code != 200:
        raise RuntimeError(f"GitHub API error listing issues: {r.status_code} {r.text}")
    for issue in r.json():
        if issue.get("title") == METRICS_ISSUE_TITLE:
            return issue.get("number")
    # Create new issue
    r = requests.post(url, json={"title": METRICS_ISSUE_TITLE, "body": "Autogenerated issue to collect agent-spec enforcement metrics."}, headers=headers)
    if r.status_code not in (200, 201):
        raise RuntimeError(f"GitHub API error creating metrics issue: {r.status_code} {r.text}")
    return r.json().get("number")


def post_metrics_to_issue(issue_number: int, metrics: Dict, token: str | None):
    headers = {"Accept": "application/vnd.github+json"}
    if token:
        headers["Authorization"] = f"token {token}"
    url = f"https://api.github.com/repos/{REPO_OWNER}/{REPO_NAME}/issues/{issue_number}/comments"
    body = (
        f"Agent-spec enforcement metrics (last {metrics['days']} days):\n"
        f"- Inspected PRs with agent changes: {metrics['inspected_prs']}\n"
        f"- Flagged PRs (missing spec): {metrics['flagged_prs']}\n"
        f"- Override label usage: {metrics['override_count']}\n"
        f"- Flagged PR numbers: {metrics['flagged_list']}\n"
        f"\nGenerated by `scripts/collect_agent_spec_metrics.py`"
    )
    r = requests.post(url, json={"body": body}, headers=headers)
    if r.status_code not in (200, 201):
        raise RuntimeError(f"GitHub API error posting metrics: {r.status_code} {r.text}")
    return r.json()


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--days", type=int, default=14)
    parser.add_argument("--post-issue", action="store_true", help="Post metrics to an issue in the repo")
    args = parser.parse_args(argv)

    token = os.environ.get("GITHUB_TOKEN", "")
    metrics = collect_metrics(args.days, token)
    print(metrics)

    if args.post_issue:
        issue_num = find_or_create_metrics_issue(token)
        post_metrics_to_issue(issue_num, metrics, token)
        print(f"Posted metrics to issue #{issue_num}")


if __name__ == "__main__":
    sys.exit(main())
